name: pytorch_wcsac
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - absl-py
  - pyparsing
  - pip:
      - termcolor
      - dm-control
      - git+git://github.com/denisyarats/dmc2gym.git
      - tb-nightly
      - imageio
      - imageio-ffmpeg
      - hydra-core==1.3.1
      - numpy==1.23.4
      - torch
      - torchvision
      - torchaudio
      - mujoco-py
      - gym==0.26.2
      - git+git://github.com/davideferrari95/safety-gym.git
