defaults:
    - agent: wcsac

# env: 'point_goal_1'
env: 'cheetah_run'
# env: 'static'

# this needs to be specified manually
experiment: exp

num_train_steps: 1e5
replay_buffer_capacity: 1e5

num_seed_steps: 1e3

eval_frequency: 5000
num_eval_episodes: 10

device: cuda

# logger
log_frequency: 3000
log_save_tb: true

# video recorder
save_video: true


seed: 1


# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}